### ISSUE TITLE
Firefox doesn't like the render 🦊

### ISSUE THREAD

**Issue by heyapricot** [zlayabekrija/admiral-s_nightmare#3]
This is what I get when I open the application with Firefox 66
![Screen Shot 2019-05-14 at 11 36 09](https://user-images.githubusercontent.com/14355495/57715560-ab908000-763c-11e9-95cd-9356f72f8bcb.png)

This issue is more of an FYI. I'll review the project using another browser (Safari)

**Comment by zlayabekrija** [comment]
Interesting will look into it definitely, thanks a lot

**Comment by zlayabekrija** [comment]
![image](https://user-images.githubusercontent.com/37313754/57719189-7fe2b980-767f-11e9-8b99-5e26baa07255.png)

With me Firefox looks ok :)

**Comment by zlayabekrija** [comment]
Fixed :)

**Comment by heyapricot** [comment]
What was the problem?

**Comment by zlayabekrija** [comment]
Didn't think beyond my display size :)
