### ISSUE TITLE
Attacking

### ISSUE THREAD

**Issue by heyapricot** [zlayabekrija/admiral-s_nightmare#6]
The way the ship receives the attack is very hacky/obscure
 1. receiveAtatck would be more readable using a [switch clause](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/switch)
2. Why do you need to check it the board has an `X` or an `M` ? Every cell on the board has only two states, `hit` or `not hit`. You are using four states: `0`, `X`, `M` and `shipName`. Why?
3.  `horAttack` and `verAttack` are almost identical. [D.R.Y.](https://www.c-sharpcorner.com/article/dont-repeat-yourselfdry-design-principle/)
4. The way the attack is done is VERY hacky/obscure. The mapping doesn't even match! Look at this: 
![Screen Shot 2019-05-15 at 06 50 15](https://user-images.githubusercontent.com/14355495/57773536-dd0d5800-76dd-11e9-9269-972fba8213a9.png)
The board is displaying the `Oasis` like this -> `['X', 'X', 'X', 'O', 'O']` but in reality it's stored like this `['X', 'O', 'O', 'X', 'X']`

**Comment by zlayabekrija** [comment]
1. I prefer if/else in this case
2 M represents the miss, while X is hit
3. Hor and Ver attacks are changed
4. Marking of array is removed
