### ISSUE TITLE
Don't repeaat yourself

### ISSUE THREAD

**Issue by heyapricot** [zlayabekrija/admiral-s_nightmare#7]
The application separates between horizontal and vertical positioning and attacking. This results in almost identical methods with only a slight variant for the position. How can these methods be refactored to avoid duplication?

I'm talking about `horizontal`, `vertical`, `horAttack` and `verAttack`

**Comment by zlayabekrija** [comment]
Horizontal and vertical attack is changed now, while for positioning I need to keep separate functions.
